package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"strings"
	"time"

	jwtauth "github.com/Ke-vin-S/ledger/api/internal/auth"
	"github.com/Ke-vin-S/ledger/api/internal/graph/model"
	"github.com/google/uuid"
)

// TeamActivityFeed is the resolver for the teamActivityFeed field.
func (r *queryResolver) TeamActivityFeed(ctx context.Context, teamID string, limit *int, cursor *string) (*model.ActivityFeedPage, error) {
	tid, err := uuid.Parse(teamID)
	if err != nil {
		return nil, fmt.Errorf("invalid teamId: %w", err)
	}
	claims := jwtauth.ClaimsFrom(ctx)
	if claims == nil {
		return nil, fmt.Errorf("unauthenticated")
	}
	actorID, err := uuid.Parse(claims.Subject)
	if err != nil {
		return nil, fmt.Errorf("invalid subject in token: %w", err)
	}
	if err := r.memberships.RequireMembership(ctx, tid, actorID, "member"); err != nil {
		return nil, err
	}

	lim := 20
	if limit != nil && *limit > 0 && *limit <= 100 {
		lim = *limit
	}

	var before *ActivityCursor
	if cursor != nil && *cursor != "" {
		tsText, idText, ok := strings.Cut(*cursor, "|")
		if ok {
			ts, tsErr := time.Parse(time.RFC3339Nano, tsText)
			id, idErr := uuid.Parse(idText)
			if tsErr == nil && idErr == nil {
				before = &ActivityCursor{Time: ts, ID: id}
			}
		}
	}

	// Fetch one extra to detect hasMore.
	entries, err := r.activityStore.QueryTeamActivityFeed(ctx, tid, lim+1, before)
	if err != nil {
		return nil, err
	}

	hasMore := len(entries) > lim
	if hasMore {
		entries = entries[:lim]
	}

	if entries == nil {
		entries = []*model.ActivityEntry{}
	}

	page := &model.ActivityFeedPage{
		Items:   entries,
		HasMore: hasMore,
	}
	if hasMore && len(entries) > 0 {
		last := entries[len(entries)-1]
		cur := last.CreatedAt + "|" + last.ID
		page.NextCursor = &cur
	}
	return page, nil
}

// DashboardAggregates is the resolver for the dashboardAggregates field.
func (r *queryResolver) DashboardAggregates(ctx context.Context) (*model.DashboardAggregates, error) {
	claims := jwtauth.ClaimsFrom(ctx)
	if claims == nil {
		return nil, fmt.Errorf("unauthenticated")
	}
	userID, err := uuid.Parse(claims.Subject)
	if err != nil {
		return nil, fmt.Errorf("invalid subject in token: %w", err)
	}
	return r.dashStore.QueryDashboardAggregates(ctx, userID)
}

// ExpenseHistory is the resolver for the expenseHistory field.
func (r *queryResolver) ExpenseHistory(ctx context.Context, expenseID string) ([]*model.ExpenseVersion, error) {
	eid, err := uuid.Parse(expenseID)
	if err != nil {
		return nil, fmt.Errorf("invalid expenseId: %w", err)
	}
	claims := jwtauth.ClaimsFrom(ctx)
	if claims == nil {
		return nil, fmt.Errorf("unauthenticated")
	}
	actorID, err := uuid.Parse(claims.Subject)
	if err != nil {
		return nil, fmt.Errorf("invalid subject in token: %w", err)
	}
	if _, err := r.expenses.GetExpense(ctx, actorID, eid); err != nil {
		return nil, err
	}

	versions, err := r.historyStore.QueryExpenseHistory(ctx, eid)
	if err != nil {
		return nil, err
	}
	if versions == nil {
		return []*model.ExpenseVersion{}, nil
	}
	return versions, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
