// Auto-generated by graphql-codegen. Run `pnpm codegen` to regenerate.
// Requires the API server running at localhost:8080.

export type Maybe<T> = T | null;
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  Map: Record<string, unknown>;
};

export type ActivityEntry = {
  __typename?: "ActivityEntry";
  id: Scalars["ID"];
  action: Scalars["String"];
  actorId?: Maybe<Scalars["ID"]>;
  entityType: Scalars["String"];
  entityId: Scalars["ID"];
  meta?: Maybe<Scalars["Map"]>;
  createdAt: Scalars["String"];
};

export type ActivityFeedPage = {
  __typename?: "ActivityFeedPage";
  items: Array<ActivityEntry>;
  nextCursor?: Maybe<Scalars["String"]>;
  hasMore: Scalars["Boolean"];
};

export type DashboardAggregates = {
  __typename?: "DashboardAggregates";
  totalOwed: Scalars["Int"];
  totalOwing: Scalars["Int"];
  netBalance: Scalars["Int"];
};

export type ExpenseVersion = {
  __typename?: "ExpenseVersion";
  id: Scalars["ID"];
  expenseId: Scalars["ID"];
  version: Scalars["Int"];
  snapshot: Scalars["Map"];
  correctedBy: Scalars["ID"];
  correctionReason?: Maybe<Scalars["String"]>;
  createdAt: Scalars["String"];
};

export type TeamActivityFeedQueryVariables = {
  teamId: Scalars["ID"];
  limit?: Maybe<Scalars["Int"]>;
  cursor?: Maybe<Scalars["String"]>;
};

export type TeamActivityFeedQuery = {
  teamActivityFeed: ActivityFeedPage;
};

export type DashboardAggregatesQuery = {
  dashboardAggregates: DashboardAggregates;
};

export type ExpenseHistoryQueryVariables = {
  expenseId: Scalars["ID"];
};

export type ExpenseHistoryQuery = {
  expenseHistory: Array<ExpenseVersion>;
};
