// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ActivityEntry struct {
	ID         string         `json:"id"`
	Action     string         `json:"action"`
	ActorID    *string        `json:"actorId,omitempty"`
	EntityType string         `json:"entityType"`
	EntityID   string         `json:"entityId"`
	Meta       map[string]any `json:"meta,omitempty"`
	CreatedAt  string         `json:"createdAt"`
}

type ActivityFeedPage struct {
	Items      []*ActivityEntry `json:"items"`
	NextCursor *string          `json:"nextCursor,omitempty"`
	HasMore    bool             `json:"hasMore"`
}

type DashboardAggregates struct {
	// Total amount others owe the caller (minor units).
	TotalOwed int `json:"totalOwed"`
	// Total amount the caller owes others (minor units).
	TotalOwing int `json:"totalOwing"`
	// totalOwed - totalOwing.
	NetBalance int `json:"netBalance"`
}

type ExpenseVersion struct {
	ID               string         `json:"id"`
	ExpenseID        string         `json:"expenseId"`
	Version          int            `json:"version"`
	Snapshot         map[string]any `json:"snapshot"`
	CorrectedBy      string         `json:"correctedBy"`
	CorrectionReason *string        `json:"correctionReason,omitempty"`
	CreatedAt        string         `json:"createdAt"`
}

type Query struct {
}
